x = Artist.objects.create(name='Black Sabbath')
y = Album.objects.create(artist=x, name='Heaven & Hell')
Track.objects.create(album=y, name='Neon Knights', index=1)
Track.objects.create(album=y, name='Children of the Sea', index=2)
Track.objects.create(album=y, name='Lady Evil', index=3)
Track.objects.create(album=y, name='Heaven and Hell', index=4)
Track.objects.create(album=y, name='Wishing Well', index=5)
Track.objects.create(album=y, name='Die Young', index=6)
Track.objects.create(album=y, name='Walk Away', index=7)
Track.objects.create(album=y, name='Lonely Is the Word', index=8)
y = Album.objects.create(artist=x, name='Mob Rules')
Track.objects.create(album=y, name='Turn Up the Night', index=1)
Track.objects.create(album=y, name='Voodoo', index=2)
Track.objects.create(album=y, name='The Sign of the Southern Cross', index=3)
Track.objects.create(album=y, name='E5150" (instrumental', index=4)
Track.objects.create(album=y, name='The Mob Rules', index=5)
Track.objects.create(album=y, name='Country Girl', index=6)
Track.objects.create(album=y, name='Slipping Away', index=7)
Track.objects.create(album=y, name='Falling Off the Edge of the World', index=8)
Track.objects.create(album=y, name='Over and Over', index=9)
x = Artist.objects.create(name='Ozzy Osbourne')
y = Album.objects.create(artist=x, name='Blizzard of Ozz')
Track.objects.create(album=y, name="I Don't Know", index=1)
Track.objects.create(album=y, name='Crazy Train', index=2)
Track.objects.create(album=y, name='Goodbye to Romance', index=3)
Track.objects.create(album=y, name='Dee', index=4)
Track.objects.create(album=y, name='Suicide Solution', index=5)
Track.objects.create(album=y, name='Mr. Crowley', index=6)
Track.objects.create(album=y, name='No Bone Movies', index=7)
Track.objects.create(album=y, name='Revelation (Mother Earth)', index=8)
Track.objects.create(album=y, name='Steal Away (The Night)', index=9)
