repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: iommi/docs__tests.py

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [ '--fix' ]
        stages: [ commit ]
      - id: ruff-format
        stages: [ commit ]
