[tox]
envlist =
    py311-django{32,40,41,42,50,52}
    py312-django{32,40,41,42,50,52,60}
    py313-django{41,42,50,52,60}
    py314-django60

[testenv]
commands = {envpython} -m pytest {posargs}
deps =
    django32: Django >= 3.2, <3.3
    django40: Django >= 4.0, <4.1
    django41: Django >= 4.1, <4.2
    django42: Django >= 4.2, <4.3
    django50: Django >= 5.0, <5.1
    django52: Django >= 5.2, <5.3
    django60: Django >= 6.0, <6.1
    -r test_requirements.txt
usedevelop = True
passenv = HOME

[testenv:django-with-jinja2]
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings_jinja2_only
commands = {envpython} -m pytest {posargs}
deps =
    django42: Django >= 4.2, <4.3
    jinja2
    -r test_requirements.txt
usedevelop = True
passenv = HOME
