# Generated by Django 2.2.18 on 2021-02-04 08:31

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',), 'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('index',), 'verbose_name': 'track', 'verbose_name_plural': 'tracks'},
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='albums',
                to='examples.Artist',
                verbose_name='artist',
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tracks',
                to='examples.Album',
                verbose_name='album',
            ),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='track',
            name='index',
            field=models.IntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
    ]
