# Generated by Django 2.2.9 on 2020-01-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_tfoo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=255)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.TFoo')),
            ],
        ),
    ]
