# Generated by Django 6.0.2 on 2026-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_remove_dummy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='published date'),
        ),
    ]
