name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        django-version: ['3.2', '4.0', '4.1', '4.2', '5.0', '5.2', '6.0']
        exclude:
          - python-version: '3.11'
            django-version: '6.0'
          - python-version: '3.13'
            django-version: '3.2'
          - python-version: '3.13'
            django-version: '4.0'
          - python-version: '3.14'
            django-version: '3.2'
          - python-version: '3.14'
            django-version: '4.0'
          - python-version: '3.14'
            django-version: '4.1'
          - python-version: '3.14'
            django-version: '4.2'
          - python-version: '3.14'
            django-version: '5.0'
          - python-version: '3.14'
            django-version: '5.2'

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --dev -p ${{ matrix.python-version }}
    - name: Run tests
      run: uv run python run_tests.py --python=${{ matrix.python-version }} --django=${{ matrix.django-version }}
